title: Nikolas Costa
logo: /assets/img/WhatsApp Image 2023-11-26 at 4.48.43 PM.jpeg
description: I Turn Numbers into Narratives for Informed Decision-Making
#show_downloads: true
theme: jekyll-theme-minimal
