title:     Nikolas Costa
logo: /assets/img/WhatsApp Image 2025-03-11 at 8.49.34 PM.jpeg
description: I Turn Numbers into Narratives for Informed Decision-Making
#show_downloads: true
theme: jekyll-theme-minimal
